[workspace]

[package]
name = "thalos-core"
version = "0.1.0"
edition = "2024"
description = "Core framework crate for the Thalos Axum+SeaORM web service scaffold"
license = "MIT"
repository = "https://github.com/zrll12/thalos"
keywords = ["axum", "sea-orm", "web", "scaffold"]
categories = ["web-programming::http-server"]

[features]
openapi = ["dep:utoipa"]
swagger-ui = ["openapi", "dep:utoipa-swagger-ui"]

[dependencies]
axum = { version = "0.8.8" }
sea-orm = { version = "2.0.0-rc.40", features = [
    "macros",
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "schema-sync",
    "entity-registry",
] }
serde = { version = "1.0", features = ["derive"] }
serde-inline-default = "1.0.1"
toml = "0.9"
dashmap = "6"
thiserror = "2.0"
tracing = "0.1"
futures = "0.3"
diff = "0.1"

#openapi (optional)
utoipa = { version = "5", features = ["axum_extras"], optional = true }
utoipa-swagger-ui = { version = "9", features = ["axum"], optional = true }
